version: "3"
services:
  jairu_db:
    image: mysql
    working_dir: /jairu/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: murphy
      MYSQL_PASSWORD: Murphy@961
      MYSQL_DATABASE: jairu
#    networks:
#      mcr_net:
#        ipv4_address: 172.30.2.10

  jairu_backend:
    image: murphy961/jairu-backend:1.0
    working_dir: /jairu/backend
    stdin_open: true
    ports:
      - 8086:8086
#    networks:
#      mcr_net:
#        ipv4_address: 172.30.2.9

#networks:
#  mcr_net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.30.2.0/24